name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: kamilarosaf  # Substitua pelo seu nome de usuário
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: '#00BFFF'         # Azul claro (DeepSkyBlue)
          color_dots: '#B0E0E6,#ADD8E6,#87CEFA,#00BFFF,#1E90FF' # tons de azul para os pontos

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
